"""create_initial_tables

Revision ID: fef87eed51fa
Revises: 
Create Date: 2026-06-20 10:50:32.248799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef87eed51fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('exchange_primary', sa.String(length=20), nullable=False),
    sa.Column('exchange_secondary', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('price_ticks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spreads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('spread_type', sa.String(length=30), nullable=True),
    sa.Column('spread_bps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('z_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spreads')
    op.drop_table('price_ticks')
    op.drop_table('assets')
    # ### end Alembic commands ###
